services:
    file_store:
        class: \PoP\FileStore\Store\FileStore
    json_file_store:
        class: \PoP\FileStore\Store\JSONFileStore
    file_renderer:
        class: \PoP\FileStore\Renderer\FileRenderer
        arguments:
            $fileStore: '@file_store'