services:
    _defaults:
        public: true
        autowire: true
    PoP\FileStore\Store\FileStoreInterface:
        class: \PoP\FileStore\Store\FileStore
        public: false
    PoP\FileStore\Store\FileStoreInterface:
        class: \PoP\FileStore\Store\JSONFileStore
    PoP\FileStore\Renderer\FileRendererInterface:
        class: \PoP\FileStore\Renderer\FileRenderer
        # arguments:
        #     $fileStore: '@file_store'
